---
- name: Install Tomcat 9, Deploy sample.war, and Start Service
  hosts: all
  become: yes
  become_user: root

  vars:
    war_source_path: /home/ubuntu/sample.war
    war_dest_path: /var/lib/tomcat9/webapps/sample.war

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Tomcat 9
      apt:
        name: tomcat9
        state: present

    - name: Deploy sample.war to Tomcat webapps
      copy:
        src: "{{ war_source_path }}"
        dest: "{{ war_dest_path }}"
        owner: root
        group: root
        mode: '644'
      notify: Restart Tomcat service

    - name: Start Tomcat service
      systemd:
        name: tomcat9
        state: started

  handlers:
    - name: Restart Tomcat service
      systemd:
        name: tomcat9
        state: restarted